Libpitt/228 visualizations
x-atlas-consortia/data-ingest-board pull request #233
Opened 2024-10-08 14:09 UTC by tjmadonna

Change log:
- Added visualization section to Datasets page
- Added modal when visualization is clicked
- Added options for d3 bar and pie charts in modal
- Added ability to apply filters from modal charts

2024-10-10 20:29 UTC, yuanzhou requested changes
@tjmadonna this looks overall very nice, we can use some tweaks
- HuBMAP doesn't have "Source Type" column, and SenNet may have other columns excluded. Saying "not enough data" can be misleading.

<img width="1077" alt="Screenshot 2024-10-10 at 3 35 58 PM" src="https://github.com/user-attachments/assets/6c55160e-34e3-4221-b50b-68c928f254e5">

- The filtering feature in the chart is confusing to me. Once the filters are set based on a given chart, the window closes and all the other charts get updated too. Opening one of the charts again, I can't tell what filters applies previously. And there's no button for me to reset the chart filters other than clicking the main page's "CLEAR FILTERS" button, which also resets all the table selections outside the charts.

- The number of small charts on main page also update based on the filtering, which is also confusing. 

- The color scales used for Legend in "Dataset Type" and "Organ Type" charts are not easy to follow. I understand this is due to there are many types. And I don't have any suggestions to improve this. @shirey @maxsibilla any thoughts?

I have some proposals:

- Hide the "Source Type" option based on `NEXT_PUBLIC_EXCLUDE_TABLE_COLUMNS`

- Separate "Reset" buttons for charts and Data Table checkboxes (used for bulk data editing and processing). 

- Move the "Bar Chart" or "Pie Chart" selection to the main page, so the users understand this applies to all the charts. 
<img width="480" alt="Screenshot 2024-10-10 at 4 21 09 PM" src="https://github.com/user-attachments/assets/ba007233-967d-4c08-abe7-0cebae2b95e0">


- Indicate the applied chart filters on the main page, for example above the small charts, say "Filtered by ...." and show a Reset button next to it. That'll make it clear to the users what criteria is used and how to reset.

- Order the Legend by count (high to low) can be more useful. It'll also help create a consistent look and feel since the Bar Chart is ordered from high to low.
![image](https://github.com/user-attachments/assets/1dfc2b2e-c745-4b51-8ccf-9ecca239db61)

2024-10-14 16:03 UTC, tjmadonna commented
@maxsibilla @yuanzhou 

I made some updates to the visualizations. I moved the chart config into the .env file. You can configure each chart in the visualization section with the label, key, and default type (`bar` or `pie`). The chart types are also now independent from each other.

For HuBMAP, add this chart config to the .env file
https://github.com/x-atlas-consortia/data-ingest-board/blob/763e68e1855c8d489eb751a2a7c2bd5c1bb2a059/src/example.env#L41

For SenNet, add this chart config to the .env file
https://github.com/x-atlas-consortia/data-ingest-board/blob/763e68e1855c8d489eb751a2a7c2bd5c1bb2a059/src/example.sennet.env#L40

2024-10-14 18:16 UTC, yuanzhou approved these changes
@tjmadonna adding the chart type and columns to configuration is a great idea!

2024-10-14 18:31 UTC, maxsibilla approved these changes

2024-10-14 18:31 UTC, merged